# Generated by Django 5.2.10 on 2026-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('instructor', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('keywords', models.CharField(help_text='Comma separated keywords (max 4)', max_length=255)),
                ('skills', models.TextField(blank=True, help_text='Skills acquired after this course', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
