# Generated by Django 5.2.10 on 2026-02-24 12:37

import django.db.models.deletion
from django.db import migrations, models


def populate_provider(apps, schema_editor):
    from django.utils.text import slugify
    import uuid

    Course = apps.get_model('course', 'Course')
    Company = apps.get_model('peeldb', 'Company')

    for course in Course.objects.all():
        provider_value = getattr(course, 'provider', None)
        if not provider_value:
            continue

        # If provider_value is already an int id (possible partial changes), skip
        try:
            int(provider_value)
            continue
        except Exception:
            pass

        name = str(provider_value).strip()
        if not name:
            continue

        company = Company.objects.filter(name=name, company_type='education').first()
        if not company:
            slug = slugify(name) or str(uuid.uuid4())[:8]
            # Ensure slug uniqueness
            orig_slug = slug
            i = 1
            while Company.objects.filter(slug=slug).exists():
                slug = f"{orig_slug}-{i}"
                i += 1

            company = Company.objects.create(
                name=name,
                address='',
                profile='',
                phone_number='0000000000',
                slug=slug,
                company_type='education',
            )

        # set the temporary FK field
        setattr(course, 'provider_tmp_id', company.id)
        course.save()


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_provider_user'),
        ('peeldb', '0076_alter_company_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='provider_tmp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provided_courses', to='peeldb.company'),
        ),
        migrations.RunPython(populate_provider, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='course',
            name='provider',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='provider_tmp',
            new_name='provider',
        ),
    ]
