# Generated by Django 5.2.10 on 2026-02-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0072_remove_facebook_github_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='internship_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='internship_meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='internship_meta_title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='internship_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='meta_title',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='page_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
