# Generated by Django 5.2.10 on 2026-02-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0073_alter_city_internship_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
