# Generated by Django 5.2.10 on 2026-02-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0074_alter_city_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('JS', 'Job Seeker'), ('EM', 'Employer'), ('ED', 'Educator')], max_length=10),
        ),
    ]
