# Generated by Django 5.2.10 on 2026-02-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peeldb', '0075_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('Consultant', 'consultant'), ('Company', 'company'), ('Education', 'education')], default='', max_length=50),
        ),
    ]
